### ISSUE TITLE
Recycler view glitch on front page fragment

### ISSUE THREAD

**Issue by ViWu** [davis123123/iNGAGE#15]
The dimensions of the null Imageviews in the thread list are being mismatched with the dimensions of the actual visible images, when the user scrolls though the list.

**Comment by davis123123** [comment]
played around with adjusting the padding, had nothing to do  with bug.
Problem: we allowed the recycler view to auto adjust size based on existing/non-existing image. When scrolling, threadview holder is recalled constantly, therefore the indexing can be wrong and it renders size even with no image. Had same problem with chat upvote/downvote.
Solution 1: manually set the adjusting for image/vs non image, do not let the recycler view do it.
Solution 2: set all threads to fixed size.

I'd go with solution 1, though it would take more work.

**Comment by ViWu** [comment]
onBindViewHolder() is called a lot since the child views are updated constantly as the view holders are being scrolled in and out of the screen. So inside of there we can check if the view holder component(s) are null. If null, we can manually set the visibility or even the size of those component(s) accordingly. So we should probably go with solution 1 and add the fixes to our adapter.

There's a huge size difference in threads with and w/o images so we can't use solution 2.

**Comment by ViWu** [comment]
Finally fixed this major issue. You need to implement checks in the onBindViewHolder() method, and set the visibility of the child components accordingly. Or else the recycler view can't keep track of the state of each individual view holder, and will re-draw the views with the wrong visibility options.
