### ISSUE TITLE
Page indicator rendering glitch

### ISSUE THREAD

**Issue by ViWu** [davis123123/iNGAGE#17]
If there are many pages and user clicks on a page that's a bit far from the current page, then the old button will not change back to its normal color. Must have something to do w/ the nature of the recycler view, how it only updating views that are currently visible.

**Comment by davis123123** [comment]
Please stop using the recyclerview's API to manage dynamic views, it is not reliable......
They become hard to fix once written a certain way and need to be redone
These things must be done by using our own code i.e
Putting the which button has been clicked in a shared preference, and render them on/off by checking
the session manager.
Look at the code for the upvote/downvote and use that as a guide, it took me a longer to time deal with that, we don't want to be fixing t he same type of mistakes over and over.

**Comment by davis123123** [comment]
I used refresh on Page fragment to fix it,
The problem is that it puts the current cursor on the latest page.
To optimize i think we should use listview instead since there shouldn't be that many pages and it does  not need re-rendering.
