### ISSUE TITLE
Gradle build time increasing

### ISSUE THREAD

**Issue by ViWu** [davis123123/iNGAGE#7]
As more features and code are added to the project, the gradle takes increasingly longer to build. Average build time lasts from anywhere from 3-6 mins on my end. Longest build time up to date with the most current version took well over 11 min! Need to find efficient ways to reduce the build time (i.e. changing/optimizing configurations), in order to improve productivity.

**Comment by davis123123** [comment]
processor intel i5-6300HQ 2.30GHz
RAM 8gb
64 bit operating system
