### ISSUE TITLE
Uploading/downloading thread images and avatar doesn't render on new server

### ISSUE THREAD

**Issue by ViWu** [davis123123/iNGAGE#9]
After migrating the server, the thread images don't show up on the front page fragment. Also, need to fix the upload/download avatar function.

**Comment by davis123123** [comment]
<?php
require "connection.php";
$user_name = $_POST["user_name"];
$image = $_POST["image"];
$avatar_link = $_POST["avatar_link"];

$decodedImage = base64_decode("$image");

$mysql_qry = "UPDATE client_users SET avatar_link = '$avatar_link' where username = '$user_name';" ;
//put into image folder in www directory
if($conn->query($mysql_qry) === TRUE){
  if(file_put_contents("images/" . $image .".JPG", $decodedImage) === TRUE){
    echo "success";
  }
  else{
    echo "fail";
  }
}
else{
  echo "Error: ". $mysql_qry . "<br>" . $conn->error;
}


 ?>

**Comment by ViWu** [comment]
Ok, I found and fixed the bug for the avatar upload/download. The issue was in the UploadAvatarHandler in the front end (no avatar_link was sent over to the database and therefore wasn't updated), as well as the download_avatar.php in the back end (error in query). Closing the issue.
